### ISSUE TITLE
Error with WRF_CMAQ

### ISSUE THREAD

**Issue by hoangnghiem72** [HathewayWill/WRF-MOSIT#30]
I try to use  WRF-MOSIT to install Weather Research & Forecasting Model CMAQ (WRF-CMAQ) on Ubuntu 22.04.3 and got the error at CMAQ installation with the following error screen and logfile.

![Screenshot from 2024-01-09 23-41-35](https://github.com/HathewayWill/WRF-MOSIT/assets/63412472/15ef0983-ed6b-4a77-9477-95f976d90634)
[WRF_CMAQ.MASTER.log](https://github.com/HathewayWill/WRF-MOSIT/files/13876542/WRF_CMAQ.MASTER.log)

Please help me to overcome the error.
Thank you a lot.

**Comment by HathewayWill** [comment]
@hoangnghiem72 

Updated the code should fix this issue.

Please confirm once you have recloned the github and tried again.

**Comment by hezisue** [comment]
I can't install WRF-CMAQ (Fig.1) successfully with the latest script either. Is it caused by the non-existence of the folder of Fig.2, how can I fix it?

![Image](https://github.com/user-attachments/assets/6946cbf6-17bf-489c-bca0-588b35e61e1d)
Fig.1
![Image](https://github.com/user-attachments/assets/dae3f41a-8d87-41d9-9e9b-c3d288d2b773)
Fig.2
